Added `no-duplicate-imports` rule
ioBroker/ioBroker.eslint-config pull request #19
Opened 2024-11-14 08:48 UTC by GermanBluefox

2024-11-14 09:25 UTC, foxriver76 commented
Is it still allowed to have a separate line for all type exports?

2024-11-17 16:15 UTC, foxriver76 commented
I personally use it sometimes when having too many type imports as the compiler removes `import type { ... } from 'xy'`syntax completely it is not bad to have it in src. I mean it is fine for me but at some point we should have a final base set of ESLint rules and not modify it to death for personal preferences.

2024-11-17 16:16 UTC, foxriver76 requested changes

2024-11-17 16:16 UTC, foxriver76 commented on eslint.config.mjs
> +    '@/no-duplicate-imports': 'error',
should be

```suggestion
    'no-duplicate-imports': 'error',
```

2024-11-17 16:21 UTC, GermanBluefox commented
> I personally use it sometimes when having too many type imports as the compiler removes `import type { ... } from 'xy'`syntax completely it is not bad to have it in src. I mean it is fine for me but at some point we should have a final base set of ESLint rules and not modify it to death for personal preferences.

Early we used airbnb rules, that was based on Google JS Style. airbnb are not more maintained any more because of eslint 9
All these rules we had there and even much more. If airbnb would be maintained again, I would use them with a great pleasure.

This PR is just to get back what we had....

2024-11-17 16:26 UTC, foxriver76 commented
> > I personally use it sometimes when having too many type imports as the compiler removes `import type { ... } from 'xy'`syntax completely it is not bad to have it in src. I mean it is fine for me but at some point we should have a final base set of ESLint rules and not modify it to death for personal preferences.
> 
> Early we used airbnb rules, that was based on Google JS Style. airbnb are not more maintained any more because of eslint 9 All these rules we had there and even much more. If airbnb would be maintained again, I would use them with a great pleasure.
> 
> This PR is just to get back what we had....

All good, just wanted to point it out.

2024-11-17 16:27 UTC, foxriver76 approved these changes

2024-11-17 16:27 UTC, merged